apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform

namePrefix: ${{values.envName}}-

commonLabels:
  env: ${{values.envName}}
  backstage.io/kubernetes-id: ${{values.componentName | dump}}
bases:
  - ../base
