apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
        - image: haproxy
          name: haproxy
          ports:
          - containerPort: 80
          resources:
            limits:
              cpu: 512m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 128Mi