apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{values.serviceName}}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ${{values.serviceName}}
  template:
    metadata:
      labels:
        app: ${{values.serviceName}}
    spec:
      containers:
        - image: ${{values.serviceName}}
          name: ${{values.serviceName}}
          ports:
          - containerPort: 80
          resources:
            limits:
              cpu: 512m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 128Mi