apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: kubernetes-service-template
  title: Kubernetes Service Template
  description: Create a new Kubernetes Service
spec:
  owner: 'user:guest'
  type: service
  parameters:
    - title: Provide some simple information
      required:
        - serviceName
        - envName
      properties:
        serviceName:
          title: Name
          type: string
          pattern: '^([a-z0-9\-]+)$'
          description: Unique name of the component
          'ui:autofocus': true
        componentName:
          title: Component Name
          description: Component Name
          type: string
          default: dev
          enum:
            - platform
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
        envName:
          title: Environment
          description: Environment to create resources
          type: string
          default: dev
          enum:
            - dev
            - stg
            - prd
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
  steps:
    - id: debug
      name: Debug message
      action: 'debug:log'
      input:
        message: '${{ parameters.serviceName }} ${{ parameters.envName }}'
    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: This is ${{ parameters.serviceName }}
        repoUrl: ${{ parameters.repoUrl }}
